pull_request_rules:
  - name: Automatic merge on Azure Pipelines and Reviewable successes
    conditions:
      - base=master
      - status-success=ycm-core.YouCompleteMe
      - status-success=code-review/reviewable
    actions:
      merge:
        method: merge
        strict: true
      comment:
        message: Thanks for sending a PR!
  - name: Manual merge on Azure Pipelines and Maintainer Override
    conditions:
      - base=master
      - status-success=ycm-core.YouCompleteMe

      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"

      - label="Ship It!"
    actions:
      merge:
        method: merge
        strict: true
      comment:
        message: Thanks for sending a PR!
